#!/bin/bash

# CPS Validation Demo Script
# Demonstrates all validation capabilities for Easypanel deployment

echo "===================================================="
echo "   CPS EASYPANEL VALIDATION SYSTEM DEMO"
echo "===================================================="
echo "Date: $(date)"
echo "Environment: Easypanel (Port 3000 + Reverse Proxy)"
echo ""

# Function to demonstrate validation script
demo_script() {
    local script_name="$1"
    local description="$2"
    
    echo "▶ $description"
    echo "   Script: $script_name"
    echo ""
    
    if [[ "$script_name" == *.php ]]; then
        echo "   Command: php $script_name"
        echo "   Description: Validates all CPS components including Laravel, database, ionCube"
        echo "   Output: Detailed validation report with recommendations"
    elif [[ "$script_name" == "quick_validate_easypanel.sh" ]]; then
        echo "   Command: bash $script_name"
        echo "   Description: Fast diagnostic check for connectivity issues"
        echo "   Output: Quick status report with error/warning counts"
    elif [[ "$script_name" == "post_deploy_validation.sh" ]]; then
        echo "   Command: bash $script_name"
        echo "   Description: Auto-validation after deploy with detailed logging"
        echo "   Output: Comprehensive logs in validation-scripts/logs/"
    elif [[ "$script_name" == "monitor_cps_easypanel.sh" ]]; then
        echo "   Command: bash $script_name --daemon --interval 30"
        echo "   Description: Continuous monitoring with alert detection"
        echo "   Output: Real-time monitoring logs"
    fi
    
    echo ""
    echo "   Expected Results:"
    echo "   ✓ Port 3000: LISTENING"
    echo "   ✓ Internal HTTP: 200/301/302"
    echo "   ✓ External HTTP: 200/301/302 (if proxy configured)"
    echo "   ✓ Database: CONNECTED"
    echo "   ✓ Redis: CONNECTED"
    echo "   ✓ ionCube: LOADED"
    echo ""
    echo "   Troubleshooting:"
    echo "   - Port 3000 not listening → Check application container"
    echo "   - Database failed → Verify MariaDB service"
    echo "   - ionCube missing → Install ionCube Loader extension"
    echo ""
    echo "===================================================="
    echo ""
}

# Function to show architecture
show_architecture() {
    echo "🏗️ EASYPANEL ARCHITECTURE"
    echo ""
    echo "   [User Request]"
    echo "         ↓"
    echo "   https://cps.qhosting.net (External)"
    echo "         ↓"
    echo "   [Easypanel Reverse Proxy]"
    echo "         ↓"
    echo "   http://localhost:3000 (Internal)"
    echo "         ↓"
    echo "   [CPS Laravel Application]"
    echo ""
    echo "   Validated Components:"
    echo "   • Application Port: 3000"
    echo "   • Database Port: 3306 (MariaDB)"
    echo "   • Redis Port: 6379"
    echo "   • PHP Extensions: ionCube Loader"
    echo ""
    echo "===================================================="
    echo ""
}

# Function to show integration
show_integration() {
    echo "🚀 INTEGRATION WITH DEPLOY PROCESS"
    echo ""
    echo "   1. Automatic Integration:"
    echo "      bash integrate_validation.sh"
    echo ""
    echo "   2. Manual Integration:"
    echo "      # Add to end of deploy.sh:"
    echo "      cd validation-scripts"
    echo "      bash post_deploy_validation.sh"
    echo ""
    echo "   3. Post-Deploy Validation:"
    echo "      bash post_deploy_validation.sh"
    echo "      cat logs/latest_status.txt"
    echo ""
    echo "   4. Continuous Monitoring:"
    echo "      bash monitor_cps_easypanel.sh --daemon --interval 60"
    echo ""
    echo "===================================================="
    echo ""
}

# Main demo
show_architecture

echo "📋 AVAILABLE VALIDATION SCRIPTS"
echo ""

demo_script "quick_validate_easypanel.sh" "Quick Diagnostic Check"
demo_script "validate_deployment_easypanel.php" "Complete System Validation"
demo_script "post_deploy_validation.sh" "Post-Deploy Auto-Validation"
demo_script "monitor_cps_easypanel.sh" "Continuous Monitoring"

show_integration

echo "🔧 QUICK START COMMANDS"
echo ""
echo "   # Run all validations"
echo "   cd validation-scripts"
echo "   bash quick_validate_easypanel.sh"
echo "   php validate_deployment_easypanel.php"
echo ""
echo "   # View results"
echo "   cat logs/latest_status.txt"
echo "   ls logs/deploy_validation_*.log"
echo ""
echo "   # Start monitoring"
echo "   bash monitor_cps_easypanel.sh --daemon --interval 30"
echo ""
echo "===================================================="
echo ""

echo "📁 FILE STRUCTURE"
echo ""
echo "validation-scripts/"
echo "├── validate_deployment_easypanel.php    # Complete validation"
echo "├── quick_validate_easypanel.sh          # Fast diagnostic"
echo "├── post_deploy_validation.sh            # Auto post-deploy"
echo "├── monitor_cps_easypanel.sh             # Continuous monitoring"
echo "├── integrate_validation.sh              # Deploy integration"
echo "├── README.md                            # Main documentation"
echo "├── EASYPANEL_VALIDATION_README.md       # Easypanel guide"
echo "├── logs/                                # Validation logs"
echo "│   ├── latest_status.txt                # Current status"
echo "│   └── deploy_validation_*.log          # Detailed logs"
echo "└── monitoring/                          # Monitoring logs"
echo "    └── monitor_*.log                    # Continuous logs"
echo ""
echo "===================================================="
echo ""

echo "📊 VALIDATION CHECKLIST"
echo ""
echo "   Post-Deploy Checklist:"
echo "   ☐ Port 3000 listening"
echo "   ☐ Internal HTTP responds (200/301/302)"
echo "   ☐ External HTTP responds (200/301/302)"
echo "   ☐ Database connected"
echo "   ☐ Redis connected"
echo "   ☐ ionCube Loader loaded"
echo "   ☐ Laravel logs clear"
echo "   ☐ Storage permissions correct"
echo "   ☐ Monitoring configured"
echo ""
echo "   Troubleshooting Commands:"
echo "   docker ps                              # Check containers"
echo "   docker logs cps-app                    # View application logs"
echo "   netstat -tuln | grep 3000              # Check port 3000"
echo "   curl -v http://localhost:3000          # Test internal connectivity"
echo "   curl -v https://cps.qhosting.net       # Test external connectivity"
echo ""
echo "===================================================="
echo ""

echo "🎯 TROUBLESHOOTING GUIDE"
echo ""
echo "   Common Issues & Solutions:"
echo ""
echo "   ❌ Port 3000 Not Listening"
echo "      → docker restart cps-app"
echo "      → Check application logs: docker logs cps-app"
echo "      → Verify .env configuration"
echo ""
echo "   ❌ Database Connection Failed"
echo "      → docker restart cps-mariadb"
echo "      → Check database credentials in .env"
echo "      → Verify MariaDB is running: docker ps"
echo ""
echo "   ❌ ionCube Loader Not Loaded"
echo "      → docker restart cps-php"
echo "      → Verify ionCube installation in PHP container"
echo "      → Check PHP extensions: docker exec cps-php php -m"
echo ""
echo "   ❌ External Access Failed (Internal OK)"
echo "      → Check Easypanel reverse proxy configuration"
echo "      → Verify domain DNS settings"
echo "      → Check SSL certificate status"
echo ""
echo "===================================================="
echo ""

echo "✅ DEMO COMPLETED"
echo ""
echo "All CPS validation scripts are ready for use!"
echo "Repository: https://github.com/qhosting/cps.git"
echo "Location: validation-scripts/"
echo ""
echo "For detailed documentation, see:"
echo "• README.md - Complete usage guide"
echo "• EASYPANEL_VALIDATION_README.md - Easypanel-specific guide"
echo ""
echo "===================================================="